#!/bin/sh
PDIR=`pwd`

rm -rf /tmp/${PNAME}
mkdir /tmp/${PNAME}
cp -r . /tmp/${PNAME}

cd /tmp/${PNAME}

echo "Building package ..."
sh gradlew build

echo "Creating package ..."
cd /tmp/${PNAME}/jgr-r/src/main/
find ${PNAME}/ -name *DS_Store* | xargs rm -rf
tar fcz "${PDIR}/../${PNAME}_${VER}.tar.gz" ${PNAME}

echo "Done."
cd ${PDIR}
ls -l ../${PNAME}_${VER}.tar.gz
