#!/bin/sh
PDIR=`pwd`

rm -rf /tmp/${PNAME}
mkdir /tmp/${PNAME}
cp -r . /tmp/${PNAME}

cd /tmp/${PNAME}

echo "Creating package ..."
sh gradlew build

cd ${PDIR}

cp /tmp/${PNAME}/jgr-r/build/distributions/${PNAME}_${VER}.tar.gz ..
echo "Done."
ls -l ../${PNAME}_${VER}.tar.gz

echo "Package content ..."
tar tf ../${PNAME}_${VER}.tar.gz

